from pt_br_verbs_lemmatizer import checkFlexVerbDuplicity,lemmatize,modifyDicAmbiguousVerbs

print(checkFlexVerbDuplicity('provemos'))
print(lemmatize('provemos'))
print(lemmatize('provemos',ignore_ambiguous_verbs=False))
print(checkFlexVerbDuplicity('provemo-lo'))
print(lemmatize('provemo-lo'))
print(lemmatize('provemo-lo',ignore_ambiguous_verbs=False))
print(checkFlexVerbDuplicity('mantemos'))
print(lemmatize('mantemos'))
print(lemmatize('mantemos',ignore_ambiguous_verbs=False))
print(checkFlexVerbDuplicity('mantemo-nos'))
print(lemmatize('mantemo-nos'))
print(lemmatize('mantemo-nos',ignore_ambiguous_verbs=False))
modifyDicAmbiguousVerbs(type='flex',verbs=[('provemos','prover'),('mantemos','manter')])
print(checkFlexVerbDuplicity('provemos'))
print(lemmatize('provemos'))
print(lemmatize('provemos',ignore_ambiguous_verbs=False))
print(checkFlexVerbDuplicity('provemo-lo'))
print(lemmatize('provemo-lo'))
print(lemmatize('provemo-lo',ignore_ambiguous_verbs=False))
print(checkFlexVerbDuplicity('mantemos'))
print(lemmatize('mantemos'))
print(lemmatize('mantemos',ignore_ambiguous_verbs=False))
print(checkFlexVerbDuplicity('mantemo-nos'))
print(lemmatize('mantemo-nos'))
print(lemmatize('mantemo-nos',ignore_ambiguous_verbs=False))